# -*- coding: utf-8 -*-
"""HTML_Quick_Styler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UFDKNEvb6PKrt06KjzfK8ss9uJILQb5n
"""

!pip install -U transformers
!pip install gradio

from google.colab import drive
drive.mount('/content/drive')

import gradio as gr
from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct"
)

messages = [
    {"role": "user", "content": "Who are you?"}
]

pipe(messages)

class ColorPaletteGenerator:

    @staticmethod
    def generate_palette(style="modern"):

        palettes = {

            "modern":{
                "primary":"#667eea",
                "secondary":"#764ba2",
                "accent":"#f093fb",
                "background":"#0f172a",
                "text":"#ffffff"
            },

            "ocean":{
                "primary":"#0099cc",
                "secondary":"#006699",
                "accent":"#00ccff",
                "background":"#0f172a",
                "text":"#ffffff"
            },

            "forest":{
                "primary":"#27ae60",
                "secondary":"#1e8449",
                "accent":"#52be80",
                "background":"#0f172a",
                "text":"#ffffff"
            }

        }

        return palettes.get(style, palettes["modern"])

def generate_html(title, description, style):

    palette = ColorPaletteGenerator.generate_palette(style)

    html = f"""
    <html>
    <head>
    <title>{title}</title>

    <style>

    body {{
    background:{palette['background']};
    color:{palette['text']};
    font-family:Arial;
    }}

    header {{
    background:{palette['primary']};
    padding:20px;
    text-align:center;
    }}

    button {{
    background:{palette['accent']};
    padding:10px 20px;
    border:none;
    color:white;
    }}

    </style>

    </head>

    <body>

    <header>
    <h1>{title}</h1>
    </header>

    <section>
    <p>{description}</p>
    <button>Get Started</button>
    </section>

    </body>

    </html>
    """

    return html

with gr.Blocks() as demo:

    gr.Markdown("# HTML Quick Styler")

    title = gr.Textbox(label="Page Title")

    description = gr.Textbox(label="Page Description")

    style = gr.Dropdown(
        ["modern","ocean","forest"],
        value="modern",
        label="Color Style"
    )

    button = gr.Button("Generate HTML")

    output = gr.Code(language="html")

    button.click(
        generate_html,
        inputs=[title, description, style],
        outputs=output
    )

demo.launch(share=True)